# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0002_consultation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=True, help_text='Determine if the user is a doctor or not', verbose_name='doctor'),
        ),
    ]
