# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0004_auto_20170612_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 20, 50, 3, 960000)),
        ),
    ]
