# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0008_auto_20170614_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 14, 9, 16, 967000)),
        ),
    ]
