# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0010_auto_20170614_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 19, 35, 18, 223000)),
        ),
    ]
